### ISSUE TITLE
Umbraco version

### ISSUE THREAD

**Issue by rnair-commits** [a2wd/UmbracoForms.ConditionalWorkflows#1]
Will this work with Umbraco version 7.12.3?

**Comment by a2wd** [comment]
I'm sorry, I haven't worked on this for some years, though if you are able to try it out please let me know if there are issues with 7.12+, I may be able to update it.

**Comment by manish-sonichealthcare** [comment]
Hi @a2wd,

This package was working on v7.15.6.
Currently on v8.12.1 and it doesn't seem to function.
Can you please have a look at this one?

Thanks,
Manish

**Comment by a2wd** [comment]
Hi Manish,

Unfortunately I do not have a lot of free time at the moment so while I may be able to address this issue, it is unlikely to happen in a timely manner.

If you are able to fix it yourself feel free to either fork the repo or submit a PR.

Kind regards

Alito

**Comment by tubbecool** [comment]
It works really well with Umbraco 11. You only need to do some minor changes to make it work with the newest version. This is basically all that has changed:

![image](https://user-images.githubusercontent.com/47563232/218690072-08ea7120-619e-4e90-a43c-3f1ecb441e81.png)

You also need to register the Workflow in a Composer.cs-class:

`    
public class Composer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.WithCollectionBuilder<WorkflowCollectionBuilder>()
                .Add<CustomEmailWorkflow>();
        }
    }
`

You'll find documentation here: https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-workflowtype

**Comment by tubbecool** [comment]
![image](https://user-images.githubusercontent.com/47563232/218694124-cf6ef813-4c2b-47f2-a7c7-bd7595d4a166.png)

Just realized this conditional feature is built-in in latest version, meaning there is no need for this workflow at all

**Comment by a2wd** [comment]
Thanks for following up on this @tubbecool, great to see this functionality included in core. I will now close the issue as it's no longer needed.
